Sprint 1
vadimfrolov/middle.messenger.praktikum.yandex pull request #1
Opened 2021-05-30 13:00 UTC by vadimfrolov

Основные страницы, логин, регистрация, окно выбора чатов, профиль, ошибки 500 и 404 представлены.
В качестве шаблонизатора использовал Handlebars.
Использовал препроцессор Less, стили разбил на модули.

Есть проблема с запуском dev версии через npm run dev с Parcel и связкой между index.html и Handlebars, буду рад помощи.

Для запуска и корректировки в реальном времени также установил nodemon - позволяет запускать проект через npm start на порту 3000.

2021-05-31 13:53 UTC, DmitryKhitrin commented on .prettierrc
> +}
EOF

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2021-05-31 14:11 UTC, DmitryKhitrin requested changes
Привет)

Спасибо за вашу работу, код выглядит достаточно аккуратно, но не очень работает на netlify, плюс я оставил некоторые комментарии;

Что бы все заелось с parcel, нужно что бы был какой-то main файл (тот же index.js), точка входа, от которого стартует проект, в котором импортируются остальные зависимые модули. На главной странице, есть [пример](https://parceljs.org/). 

Если понимаешь, что совсем ничего не понятно, это нормально) Всегда можно написать ментору, он поможет разобраться!)

Удачи!

2021-05-31 14:11 UTC, khitrind commented on dist/index.html
> +<!DOCTYPE html><html lang="en"><head><title>Chat html</title><meta charset="utf-8"><link rel="stylesheet/less" type="text/css" href="/style.bb511a86.css"><script src="//cdn.jsdelivr.net/npm/less@3.13
EOF

2021-05-31 14:11 UTC, khitrind commented on dist/script.61c6d1aa.js
> +// modules are defined as an array
Не стоит держать под версией собранные файлы, проект всегда можно поднять из исходников. Папку dist стоит добавить в `.gitignore`

2021-05-31 14:11 UTC, khitrind commented on server.js
> +        message: [
Моки лучше вынести в отдельный файл

2021-05-31 14:11 UTC, khitrind commented on src/components/script.js
> +}
EOF

2021-05-31 14:11 UTC, khitrind commented on src/test.js
> +const root = document.querySelector('#root');
Для тестирования хорошо подойдет https://jestjs.io/ru/

2021-05-31 14:11 UTC, khitrind commented on src/utils/logger.js
> +  item.addEventListener("input", function () {
По ТЗ необходимо вывести данные формы в объекте, а не отдельными строками:

`Array.from(document.querySelectorAll('.login-input')).reduce((acc, {name, value}) => {acc[name] = value; return acc}, {})`

2021-05-31 14:11 UTC, khitrind commented on style.less
> +}
EOF

2021-05-31 14:11 UTC, DmitryKhitrin commented on README.md
> +### Netlify https://stoic-spence-e5d073.netlify.app/
Страница по ссылке недоступна(

2021-05-31 14:11 UTC, DmitryKhitrin commented on README.md
> +###  Есть проблема с запуском dev версии в через npm run dev и связкой между index.html и Handlebars.
В самом простом варианте, можно сделать так:

1) На каждый страницу свой index.html, который подключает свой скрипт
2) В скрипте, запускается:

const template = Handlebars.compile("Handlebars <b>{{doesWhat}}</b>");
const component = template({ doesWhat: "rocks!" });
Далее вставка компонента в html блок

-----------------------

2021-05-31 14:12 UTC, DmitryKhitrin commented on package.json
> +    "dev": "./node_modules/.bin/parcel ./index.html",
`"dev": "parcel ./index.html"`

2021-06-04 10:24 UTC, vadimfrolov commented on .prettierrc
> +}
добавил в Prettier настройку "endOfLine": "lf"

2021-06-04 10:24 UTC, vadimfrolov commented on dist/index.html
> +<!DOCTYPE html><html lang="en"><head><title>Chat html</title><meta charset="utf-8"><link rel="stylesheet/less" type="text/css" href="/style.bb511a86.css"><script src="//cdn.jsdelivr.net/npm/less@3.13
добавил в Prettier настройку "endOfLine": "lf"

2021-06-04 10:24 UTC, vadimfrolov commented on dist/script.61c6d1aa.js
> +// modules are defined as an array
убрал из кэша git папку dist, и добавил её в .gitignore

2021-06-04 10:24 UTC, vadimfrolov commented on server.js
> +        message: [
для рендера данных через app вынес мокап данные в data.js и formData.js

2021-06-04 10:25 UTC, vadimfrolov commented on src/components/script.js
> +}
добавил в Prettier настройку "endOfLine": "lf"

2021-06-04 10:25 UTC, vadimfrolov commented on src/utils/logger.js
> +  item.addEventListener("input", function () {
данные из форм теперь в общем массиве из name и value

2021-06-04 10:25 UTC, vadimfrolov commented on README.md
> +### Netlify https://stoic-spence-e5d073.netlify.app/
Страница на Netlify теперь доступна https://stoic-spence-e5d073.netlify.app/

2021-06-04 10:25 UTC, vadimfrolov commented on README.md
> +###  Есть проблема с запуском dev версии в через npm run dev и связкой между index.html и Handlebars.
подключил handlebars в 2х html файлах signup и chat, в дальнейшем, когда будет понятно как нужно будет сделать для этого приложения роутинг и прочии функции, структура может поменяться

2021-06-04 10:25 UTC, vadimfrolov commented on package.json
> +    "dev": "./node_modules/.bin/parcel ./index.html",
npm run dev - теперь работает

2021-06-04 10:30 UTC, closed without merging