Sprint 4
vadimfrolov/middle.messenger.praktikum.yandex pull request #11
Opened 2021-07-19 19:46 UTC by vadimfrolov

19.07

добавил Docker
добавил настройки webpack
добавл husky
обновил npm пакеты
Heroku - https://protected-atoll-47793.herokuapp.com/

2021-07-20 09:36 UTC, nickchamel requested changes
Привет! Несмотря на то, что комментарии которые я оставил - это по желанию, потому что в задании этого нет, работу я вынужден вернуть как минимум по причине того, что я захожу ее посмотреть - а она не работает.
![image](https://user-images.githubusercontent.com/28347933/126297718-7279637b-f5d5-4d63-ad7e-c70194c43163.png)
Нужно как минимум обработать кейс когда запрос на юзера возвращается с 401 ошибкой и редиректить на логин в таком случае.
С регистрацией вроде все ок, создание чатов и тп тоже ок, но я не вижу у тебя страницы логина и профиля. Их нет в роутере, и в разметке нет нигде на них никаких ссылок, по заданию они должны быть

2021-07-20 09:36 UTC, nickchamel commented on src/pages/chat/chat.ts
> +import { ActionTypes, GlobalStore } from "../../utils/store";
тут внезапно ты стал использовать двойные кавычки, лучше придерживаться одного стиля

2021-07-20 09:36 UTC, nickchamel commented on src/pages/chat/chat.ts
>      const avatarSrc = selectedChat?.avatar;
Разве должен быть `chatList` типа `unknown`
Это как бы сказать неправильное использование тайпскрипта в принципе.
он должен помогать, а тут какой в нем смысл получается?
А дальше через 1 строку ты делаешь type assertion для чатлиста. Так может как минимум сразу указать
`const chatList: <Record<string, unknown>[]> = GlobalStore.get("chatList");`?
и тогда тебе не придется делать type assertion. А ты его делаешь практически повсеместно по всему коду.
Это неправильное применение тайпскрипта. Тайпскрипт должен тебе говорить где какой тип данных должен быть. А у тебя получается все наоборот - ты говоришь тайпскрипту что здесь, там и тд.. такой то тип данных. type assertion для исключительных случаев. Старайся использовать обычную типизацию данных.
Вообще я пробежался по коду и вижу, что тебе неплохо было бы весь код правильно покрыть типами, потому что с этим есть реальная проблемка. Вот например тот же стор если взять. Насколько я понимаю он у тебя типа Record<string, unknown>, а по идее он должен иметь конкретный интерфейс, например
```
interface IStore {
...
chatList: IChat[];
...
}

interface IChat {
...
id: nubmer;
// и все остальное что есть у объекта чата
...
}
```

2021-07-20 09:36 UTC, nickchamel commented on src/pages/chat/chat.ts
> +                (<IChatPageOptions>this.props).modalWindowRenameChat.props
Опять буквально везде используется type assertion. Здесь из-за этого даже просто код читать и поддерживать сложно.
Ты можешь типизировать this.props, например так:
![image](https://user-images.githubusercontent.com/28347933/126296490-ba4cb617-bad4-4e3c-883d-52f72ed022e8.png)
Тогда тебе не придется все это писать и на все это смотреть)
Вообщем тут смотри - по заданию этого нет, ты можешь оставить все так как написал. Это я тебе в принципе говорю. Если бы это был реальный проект, то такой код ну вообще никак бы не прошел ревью) поэтому потом для себя как минимум можешь с этим поиграться, а верней научиться правильно описывать типы.

2021-07-20 16:34 UTC, vadimfrolov commented
> Привет! Несмотря на то, что комментарии которые я оставил - это по желанию, потому что в задании этого нет, работу я вынужден вернуть как минимум по причине того, что я захожу ее посмотреть - а она не работает.
> ![image](https://user-images.githubusercontent.com/28347933/126297718-7279637b-f5d5-4d63-ad7e-c70194c43163.png)
> Нужно как минимум обработать кейс когда запрос на юзера возвращается с 401 ошибкой и редиректить на логин в таком случае.
> С регистрацией вроде все ок, создание чатов и тп тоже ок, но я не вижу у тебя страницы логина и профиля. Их нет в роутере, и в разметке нет нигде на них никаких ссылок, по заданию они должны быть


Добрый день, Никита!

Спасибо за ревью, 

Я накосячил с обработкой ошибок и скрыл кнопку перехода на профиль, сейчас всё поправил.

По поводу использования типов - хорошее замечание, постараюсь поправить на каникулах и сделать правильно в следующем проекте.

Буду очень признателен, если засчитаете работу.

<img width="560" alt="Screenshot 2021-07-20 at 17 57 50" src="https://user-images.githubusercontent.com/46858187/126360913-b4b6f450-040e-4293-b4b4-1ecb42a381fd.png">
<img width="1678" alt="Screenshot 2021-07-20 at 19 25 55" src="https://user-images.githubusercontent.com/46858187/126360850-1451a4f0-7302-4095-be01-aa3b891f2034.png">
<img width="1678" alt="Screenshot 2021-07-20 at 19 26 45" src="https://user-images.githubusercontent.com/46858187/126360857-d1fdd711-1783-42e1-94a4-e11073edd820.png">

2021-07-21 13:33 UTC, nickchamel requested changes
Привет! Я с удовольствием приму твою работу) но все-таки задание есть задание и оно должно работать. Согласен?
Вот это не критично. Это я тебе так оставлю на заметку, хотя лучше конечно все-равно поправить. Если что email валидный (его не существует но сам адрес валидный)
![image](https://user-images.githubusercontent.com/28347933/126496995-e08868fc-1956-45b7-a881-57d7110a4865.png)
А вот это критично, это нужно поправить:
![image](https://user-images.githubusercontent.com/28347933/126497176-6e47615b-9619-40f0-bf67-98a77d4905d1.png)
![image](https://user-images.githubusercontent.com/28347933/126497211-a1296b00-9b5d-4f10-ba1b-3c4337d51d92.png)
Чаты приходят, что-то у тебя там с парсингом

2021-07-21 16:07 UTC, vadimfrolov commented
> Привет! Я с удовольствием приму твою работу) но все-таки задание есть задание и оно должно работать. Согласен?
> Вот это не критично. Это я тебе так оставлю на заметку, хотя лучше конечно все-равно поправить. Если что email валидный (его не существует но сам адрес валидный)
> ![image](https://user-images.githubusercontent.com/28347933/126496995-e08868fc-1956-45b7-a881-57d7110a4865.png)
> А вот это критично, это нужно поправить:
> ![image](https://user-images.githubusercontent.com/28347933/126497176-6e47615b-9619-40f0-bf67-98a77d4905d1.png)
> ![image](https://user-images.githubusercontent.com/28347933/126497211-a1296b00-9b5d-4f10-ba1b-3c4337d51d92.png)
> Чаты приходят, что-то у тебя там с парсингом

Понял.
<img width="532" alt="Screenshot 2021-07-21 at 18 58 21" src="https://user-images.githubusercontent.com/46858187/126522092-ebee1355-b96f-471a-849b-69a8b7587276.png">

- поправил баг с парсингом сообщений
- улучшил правила валидации почты и номера телефона

2021-07-21 17:07 UTC, nickchamel approved these changes
Отлично! Работу принял, удачи в след модуле!

2021-07-21 17:07 UTC, nickchamel commented on src/services/chatServices.ts
> +      // chat.last_message = JSON.parse(<string>chat.last_message);
не уверен, что это можно назвать "поправил" :)
Возможно ошибка в этом:
![image](https://user-images.githubusercontent.com/28347933/126529248-50b05121-8574-4724-8bcb-bb352455a54e.png)
В таком случае нормально писать `JSON.parse(chat.last_message || '{}')`,
а вообще насколько я вижу ты мапом проходишься по parsedChats, а значит отдельно last_message потом парсить не нужно, так как там обычная строка будет (если конечно в last_message с бэка не приходит json)
![image](https://user-images.githubusercontent.com/28347933/126529494-c5d7a534-c034-402c-99f1-da514be9f030.png)

2021-07-21 17:14 UTC, nickchamel commented on src/services/chatServices.ts
> +      // chat.last_message = JSON.parse(<string>chat.last_message);
Update: да там с бэка json приходит. если нет то null.
JSON.parse(null) вернет null, а вот после парсинга всех чатов у тебя в last_message уже лежат объекты,
а JSON.parse({}) выдаст ошибку, то есть по идее здесь достаточно просто вернуть parsedChats

2026-01-28 21:25 UTC, closed without merging